title: Pacman Treasure Hunt of the Pi Terminal
hero_image: images/banner.png
description: 
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 4
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Your mission
- title: Start the treasure hunt
- title: Move around the pi terminal
- title: Catch and quarantine ghosts
- title: Find the treasure