---
title: Pac-Man treasure hunt on the terminal
hero_image: images/banner.png
description: Hack your Raspberry Pi's terminal to find all the Pac-Man ghosts
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: ''
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps:
- title: What you will make
- title: Your mission
- title: Start the treasure hunt
- title: Move around the Raspberry Pi terminal
  completion:
  - engaged
- title: Catch your first ghost
- title: Catch all the ghosts
- title: Find the treasure
  completion:
  - internal
- title: 'Challenge: get rid of the quarantine directory'
  challenge: true
  completion:
  - external
- title: What next?
