title: Pacman treasure hunt on the terminal
hero_image: images/banner.png
description: Hack your Pi's terminal to find all the Pacman ghosts
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: ''
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Your mission
- title: Start the treasure hunt
- title: Move around the Pi terminal
- title: Catch your first ghost
- title: Catch all the ghosts
- title: Find the treasure
- title: "Challenge: get rid of the quarantine folder"
