#!/bin/sh

wget url/8linky.txt -P /home/pi/Pictures
wget url/PiNkY.txt -P /home/pi/Desktop
wget url/1nky.txt -P /home/pi/Templates
wget url/CLYDE.txt -P /home/pi/python_games
wget url/sp00ky.txt -P /home/pi/Documents
wget url/funky.txt -P /home/pi/Documents/Greenfoot Projects
wget url/sue.txt -P /home/pi/Music

wget url/PacDot1 -P /home/pi/Templates
wget url/PacDot2 -P /home/pi/Pictures
wget url/PacDot3 -P /home/pi/Music
wget url/PacDot4 -P /home/pi/BlueJ Projects
wget url/PacDot5 -P /home/pi/Documents
wget url/PacDot6 -P /home/pi/Videos
wget url/PacDot7 -P /home/pi/python_games
wget url/PacDot8 -P /home/pi/Documents
wget url/PacDot9 -P /home/pi/Music
