---
title: Pac-Man-Schatzsuche im Terminal
hero_image: images/banner.png
description: Hacke das Terminal deines Pis, um alle Pac-Man-Geister zu finden
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: ''
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps:
- title: Einleitung
- title: Deine Mission
- title: Beginne die Schatzsuche
- title: Bewege dich im Pi-Terminal
  completion:
  - engaged
- title: Fange deinen ersten Geist
- title: Fange alle Geister
- title: Finde den Schatz
  completion:
  - internal