---
title: Pac-Man-Schatzsuche im Terminal
hero_image: images/banner.png
description: Hack your Raspberry Pi's terminal to find all the Pac-Man ghosts
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: ''
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: What you will make
  - 
    title: Deine Mission
  - 
    title: Beginne die Schatzsuche
  - 
    title: Move around the Raspberry Pi terminal
    completion:
      - engaged
  - 
    title: Fange deinen ersten Geist
  - 
    title: Fange alle Geister
  - 
    title: Finde den Schatz
    completion:
      - internal
  - 
    title: 'Challenge: get rid of the quarantine directory'
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
